language: python

services:
- postgresql

python:
    - "2.7"

env:
    - DJANGO_VERSION=1.7 DB=mysql

install:
#    - pip install . --use-mirrors
    - pip install -r requirements.txt
    - pip install mysql-python

before_script:
   - mysql -e 'create database IF NOT EXISTS expenses_db;' -uroot
   #- mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'sanix'@'localhost' IDENTIFIED BY 'pyp@ss';" 
   - mysql -e "GRANT ALL PRIVILEGES ON *.* TO 'root'@'localhost';" -uroot
   - python manage.py migrate

 
script:
    - python manage.py test

notifications:
    email:
        recipients:
            -sajaynix@gmail.com
        on_success: always
        on_failure: always
